# Data Cleaning

In [40]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [41]:
data = pd.read_csv("train.csv")

/var/folders/59/_p591lf10hg7b3qdvhwx3cf00000gn/T/ipykernel_20811/457307528.py:1: DtypeWarning: Columns (0: postal) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("train.csv")

In [42]:
data.shape

(150634, 78)

In [43]:
subset_df = data.iloc[ : , 0:40] # not inclusive of 40
subset_df.shape

(150634, 40)

In [44]:
subset_df.head(10)

# each row represents a transaction for a resale flat, with data on the transaction 
# (month and year, how much, information about the flat and factors around the flat)

,id,Tranc_YearMonth,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,Tranc_Year,Tranc_Month,mid_storey,lower,upper,mid,full_flat_type,address,floor_area_sqft,price_per_sqft,hdb_age,max_floor_lvl,year_completed,residential,commercial,market_hawker,multistorey_carpark,precinct_pavilion,total_dwelling_units,1room_sold,2room_sold,3room_sold,4room_sold,5room_sold,exec_sold,multigen_sold,studio_apartment_sold,1room_rental,2room_rental
0,88471,2016-05,KALLANG/WHAMPOA,4 ROOM,3B,UPP BOON KENG RD,10 TO 12,90.0,Model A,2006,680000.0,2016,5,11,10,12,11,4 ROOM Model A,"3B, UPP BOON KENG RD",968.760,701.928238,15,25,2005,Y,N,N,N,N,142,0,0,0,96,46,0,0,0,0,0
1,122598,2012-07,BISHAN,5 ROOM,153,BISHAN ST 13,07 TO 09,130.0,Improved,1987,665000.0,2012,7,8,7,9,8,5 ROOM Improved,"153, BISHAN ST 13",1399.320,475.230826,34,9,1987,Y,N,N,N,N,112,0,0,0,56,56,0,0,0,0,0
2,170897,2013-07,BUKIT BATOK,EXECUTIVE,289B,BT BATOK ST 25,13 TO 15,144.0,Apartment,1997,838000.0,2013,7,14,13,15,14,EXECUTIVE Apartment,"289B, BT BATOK ST 25",1550.016,540.639580,24,16,1996,Y,N,N,N,N,90,0,0,0,0,30,60,0,0,0,0
3,86070,2012-04,BISHAN,4 ROOM,232,BISHAN ST 22,01 TO 05,103.0,Model A,1992,550000.0,2012,4,3,1,5,3,4 ROOM Model A,"232, BISHAN ST 22",1108.692,496.080066,29,11,1990,Y,Y,N,N,N,75,0,0,0,68,7,0,0,0,0,0
4,153632,2017-12,YISHUN,4 ROOM,876,YISHUN ST 81,01 TO 03,83.0,Simplified,1987,298000.0,2017,12,2,1,3,2,4 ROOM Simplified,"876, YISHUN ST 81",893.412,333.552717,34,4,1987,Y,N,N,N,N,48,0,0,0,30,18,0,0,0,0,0
5,26610,2013-01,GEYLANG,3 ROOM,95,ALJUNIED CRES,07 TO 09,65.0,Improved,1975,335000.0,2013,1,8,7,9,8,3 ROOM Improved,"95, ALJUNIED CRES",699.660,478.803991,46,12,1974,Y,Y,N,N,N,193,0,0,188,0,5,0,0,0,0,0
6,173300,2018-05,HOUGANG,5 ROOM,641,HOUGANG AVE 8,07 TO 09,120.0,Improved,1987,433000.0,2018,5,8,7,9,8,5 ROOM Improved,"641, HOUGANG AVE 8",1291.680,335.222346,34,17,1986,Y,N,N,N,N,64,0,0,0,0,64,0,0,0,0,0
7,55093,2012-03,BEDOK,3 ROOM,701,BEDOK RESERVOIR RD,06 TO 10,68.0,New Generation,1980,340000.0,2012,3,8,6,10,8,3 ROOM New Generation,"701, BEDOK RESERVOIR RD",731.952,464.511334,41,12,1980,Y,Y,N,N,N,132,0,0,110,22,0,0,0,0,0,0
8,166738,2020-01,BISHAN,5 ROOM,450,SIN MING AVE,10 TO 12,125.0,Improved,1989,700000.0,2020,1,11,10,12,11,5 ROOM Improved,"450, SIN MING AVE",1345.500,520.252694,32,25,1988,Y,N,N,N,N,92,0,0,0,0,84,8,0,0,0,0
9,103385,2014-06,SENGKANG,5 ROOM,307D,ANCHORVALE RD,10 TO 12,110.0,Improved,2001,490000.0,2014,6,11,10,12,11,5 ROOM Improved,"307D, ANCHORVALE RD",1184.040,413.837370,20,17,2000,Y,N,N,N,N,96,0,0,0,32,64,0,0,0,0,0

### Data Types

In [45]:
subset_df.dtypes

# change Tranc_YearMonth from str  to date time format (NO NEED, there's Tranc_Year and Tranc_Month)
# lease_commence_date to date YYYY-01-01


# ADDITIONAL 
# change town to camel case

id                         int64
Tranc_YearMonth              str
town                         str
flat_type                    str
block                        str
street_name                  str
storey_range                 str
floor_area_sqm           float64
flat_model                   str
lease_commence_date        int64
resale_price             float64
Tranc_Year                 int64
Tranc_Month                int64
mid_storey                 int64
lower                      int64
upper                      int64
mid                        int64
full_flat_type               str
address                      str
floor_area_sqft          float64
price_per_sqft           float64
hdb_age                    int64
max_floor_lvl              int64
year_completed             int64
residential                  str
commercial                   str
market_hawker                str
multistorey_carpark          str
precinct_pavilion            str
total_dwelling_units       int64
1room_sold                 int64
2room_sold                 int64
3room_sold                 int64
4room_sold                 int64
5room_sold                 int64
exec_sold                  int64
multigen_sold              int64
studio_apartment_sold      int64
1room_rental               int64
2room_rental               int64
dtype: object

### Inspection

In [46]:
subset_df['id'].nunique()

# no duplicate transactions

150634

In [47]:
subset_df.info()

# no missing data in the rows

<class 'pandas.DataFrame'>
RangeIndex: 150634 entries, 0 to 150633
Data columns (total 40 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   id                     150634 non-null  int64
 1   Tranc_YearMonth        150634 non-null  str
 2   town                   150634 non-null  str
 3   flat_type              150634 non-null  str
 4   block                  150634 non-null  str
 5   street_name            150634 non-null  str
 6   storey_range           150634 non-null  str
 7   floor_area_sqm         150634 non-null  float64
 8   flat_model             150634 non-null  str
 9   lease_commence_date    150634 non-null  int64
 10  resale_price           150634 non-null  float64
 11  Tranc_Year             150634 non-null  int64
 12  Tranc_Month            150634 non-null  int64
 13  mid_storey             150634 non-null  int64
 14  lower                  150634 non-null  int64
 15  upper                  150634 non-null  int64
 16  mid                    150634 non-null  int64
 17  full_flat_type         150634 non-null  str
 18  address                150634 non-null  str
 19  floor_area_sqft        150634 non-null  float64
 20  price_per_sqft         150634 non-null  float64
 21  hdb_age                150634 non-null  int64
 22  max_floor_lvl          150634 non-null  int64
 23  year_completed         150634 non-null  int64
 24  residential            150634 non-null  str
 25  commercial             150634 non-null  str
 26  market_hawker          150634 non-null  str
 27  multistorey_carpark    150634 non-null  str
 28  precinct_pavilion      150634 non-null  str
 29  total_dwelling_units   150634 non-null  int64
 30  1room_sold             150634 non-null  int64
 31  2room_sold             150634 non-null  int64
 32  3room_sold             150634 non-null  int64
 33  4room_sold             150634 non-null  int64
 34  5room_sold             150634 non-null  int64
 35  exec_sold              150634 non-null  int64
 36  multigen_sold          150634 non-null  int64
 37  studio_apartment_sold  150634 non-null  int64
 38  1room_rental           150634 non-null  int64
 39  2room_rental           150634 non-null  int64
dtypes: float64(4), int64(22), str(14)
memory usage: 46.0 MB

### Checking for errors

In [48]:
subset_df["t-year"] = subset_df["Tranc_YearMonth"].str.split('-').str[0]
subset_df["t-month"] = subset_df["Tranc_YearMonth"].str.split('-').str[1]

In [49]:
subset_df[subset_df["t-year"] == subset_df["Tranc_Year"]]

#  Tranc_Year check correct

Empty DataFrame
Columns: [id, Tranc_YearMonth, town, flat_type, block, street_name, storey_range, floor_area_sqm, flat_model, lease_commence_date, resale_price, Tranc_Year, Tranc_Month, mid_storey, lower, upper, mid, full_flat_type, address, floor_area_sqft, price_per_sqft, hdb_age, max_floor_lvl, year_completed, residential, commercial, market_hawker, multistorey_carpark, precinct_pavilion, total_dwelling_units, 1room_sold, 2room_sold, 3room_sold, 4room_sold, 5room_sold, exec_sold, multigen_sold, studio_apartment_sold, 1room_rental, 2room_rental, t-year, t-month]
Index: []

In [50]:
subset_df[subset_df["t-month"] == subset_df["Tranc_Month"]]

# Tranc_Month check correct

Empty DataFrame
Columns: [id, Tranc_YearMonth, town, flat_type, block, street_name, storey_range, floor_area_sqm, flat_model, lease_commence_date, resale_price, Tranc_Year, Tranc_Month, mid_storey, lower, upper, mid, full_flat_type, address, floor_area_sqft, price_per_sqft, hdb_age, max_floor_lvl, year_completed, residential, commercial, market_hawker, multistorey_carpark, precinct_pavilion, total_dwelling_units, 1room_sold, 2room_sold, 3room_sold, 4room_sold, 5room_sold, exec_sold, multigen_sold, studio_apartment_sold, 1room_rental, 2room_rental, t-year, t-month]
Index: []

In [51]:
print(f" No. of unique values in town is {subset_df['town'].nunique()}")
subset_df['town'].unique()

 No. of unique values in town is 26

<StringArray>
['KALLANG/WHAMPOA',          'BISHAN',     'BUKIT BATOK',          'YISHUN',
         'GEYLANG',         'HOUGANG',           'BEDOK',        'SENGKANG',
        'TAMPINES',       'SERANGOON',     'BUKIT MERAH',   'BUKIT PANJANG',
       'WOODLANDS',     'JURONG WEST',       'TOA PAYOH',   'CHOA CHU KANG',
       'SEMBAWANG',      'ANG MO KIO',       'PASIR RIS',        'CLEMENTI',
         'PUNGGOL',     'JURONG EAST',    'CENTRAL AREA',      'QUEENSTOWN',
     'BUKIT TIMAH',   'MARINE PARADE']
Length: 26, dtype: str

In [52]:
subset_df['hdb_age'].describe()

# data for hdb_age looks ok

count    150634.000000
mean         28.551536
std          12.138829
min           2.000000
25%          20.000000
50%          29.000000
75%          37.000000
max          55.000000
Name: hdb_age, dtype: float64

In [53]:
subset_df[subset_df['hdb_age'] < 5]

,id,Tranc_YearMonth,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price,Tranc_Year,Tranc_Month,mid_storey,lower,upper,mid,full_flat_type,address,floor_area_sqft,price_per_sqft,hdb_age,max_floor_lvl,year_completed,residential,commercial,market_hawker,multistorey_carpark,precinct_pavilion,total_dwelling_units,1room_sold,2room_sold,3room_sold,4room_sold,5room_sold,exec_sold,multigen_sold,studio_apartment_sold,1room_rental,2room_rental,t-year,t-month
321,163733,2021-03,CHOA CHU KANG,4 ROOM,815C,CHOA CHU KANG AVE 7,19 TO 21,93.0,Model A,2017,495000.0,2021,3,20,19,21,20,4 ROOM Model A,"815C, CHOA CHU KANG AVE 7",1001.052,494.479807,4,20,2016,Y,N,N,N,N,190,0,0,0,95,95,0,0,0,0,0,2021,03
643,68382,2021-02,PUNGGOL,4 ROOM,122A,EDGEDALE PLAINS,10 TO 12,93.0,Model A,2017,455000.0,2021,2,11,10,12,11,4 ROOM Model A,"122A, EDGEDALE PLAINS",1001.052,454.521843,4,17,2016,Y,Y,N,N,N,144,0,0,32,80,32,0,0,0,0,0,2021,02
691,68193,2020-12,CLEMENTI,3 ROOM,440A,CLEMENTI AVE 3,10 TO 12,69.0,Model A,2018,598000.0,2020,12,11,10,12,11,3 ROOM Model A,"440A, CLEMENTI AVE 3",742.716,805.152979,3,30,2017,Y,N,N,N,N,208,0,54,102,52,0,0,0,0,0,0,2020,12
835,163614,2021-03,TAMPINES,4 ROOM,871B,TAMPINES ST 86,07 TO 09,94.0,Model A,2017,580000.0,2021,3,8,7,9,8,4 ROOM Model A,"871B, TAMPINES ST 86",1011.816,573.226753,4,16,2015,Y,N,N,N,N,135,0,0,0,90,45,0,0,0,0,0,2021,03
1092,68183,2021-02,CHOA CHU KANG,3 ROOM,803A,KEAT HONG CL,04 TO 06,68.0,Model A,2017,365000.0,2021,2,5,4,6,5,3 ROOM Model A,"803A, KEAT HONG CL",731.952,498.666579,4,14,2015,Y,N,N,N,N,113,0,0,26,87,0,0,0,0,0,0,2021,02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148371,68303,2021-02,PUNGGOL,4 ROOM,315A,PUNGGOL WAY,07 TO 09,93.0,Premium Apartment,2017,535000.0,2021,2,8,7,9,8,4 ROOM Premium Apartment,"315A, PUNGGOL WAY",1001.052,534.437771,4,18,2016,Y,N,N,N,N,160,0,0,64,64,32,0,0,0,0,0,2021,02
148710,163696,2021-04,SENGKANG,4 ROOM,163B,RIVERVALE CRES,13 TO 15,93.0,Model A,2017,470000.0,2021,4,14,13,15,14,4 ROOM Model A,"163B, RIVERVALE CRES",1001.052,469.506080,4,18,2015,Y,N,N,N,N,68,0,0,0,34,34,0,0,0,0,0,2021,04
149246,5913,2021-03,CHOA CHU KANG,2 ROOM,807A,CHOA CHU KANG AVE 1,07 TO 09,47.0,Model A,2017,256000.0,2021,3,8,7,9,8,2 ROOM Model A,"807A, CHOA CHU KANG AVE 1",505.908,506.020858,4,15,2015,Y,N,N,N,N,154,0,70,84,0,0,0,0,0,0,0,2021,03
149736,163509,2021-01,SENGKANG,5 ROOM,164A,RIVERVALE CRES,10 TO 12,113.0,Improved,2017,545000.0,2021,1,11,10,12,11,5 ROOM Improved,"164A, RIVERVALE CRES",1216.332,448.068455,4,18,2015,Y,N,N,N,N,102,0,0,0,51,51,0,0,0,0,0,2021,01
150296,68302,2021-01,PUNGGOL,3 ROOM,315A,PUNGGOL WAY,13 TO 15,68.0,Premium Apartment,2017,388000.0,2021,1,14,13,15,14,3 ROOM Premium Apartment,"315A, PUNGGOL WAY",731.952,530.089405,4,18,2016,Y,N,N,N,N,160,0,0,64,64,32,0,0,0,0,0,2021,01

### Merge with Part 2 (cleaned) and Research (new columns)

In [54]:
part2 = pd.read_csv("clean_part2.csv")
research1 = pd.read_csv("hdb_absd_foreigner_2nd_loan.csv")
research2 = pd.read_csv("hdb_bto_mop.csv")

/var/folders/59/_p591lf10hg7b3qdvhwx3cf00000gn/T/ipykernel_20811/2925665182.py:1: DtypeWarning: Columns (0: postal) have mixed types. Specify dtype option on import or set low_memory=False.
  part2 = pd.read_csv("clean_part2.csv")

In [55]:
part1 = data.iloc[ : , 0:40]

In [56]:
cleaned_df = pd.merge(part1, part2, left_index=True, right_index=True, how='inner')

In [69]:
research1.shape

(27, 21)

In [70]:
research2.shape

(27, 13)

In [64]:
r1_cols = ['Tranc_Year', 'absd_foreigner', 'ltv_limit_2nd_loan']
research1_df = research1[r1_cols]

In [65]:
r2_cols = ['Tranc_Year','bto_launched', 'mop_flats']
research2_df = research2[r2_cols]

In [71]:
research_df = pd.merge(research1_df, research2_df, on='Tranc_Year')
research_df.shape

(27, 5)

In [72]:
combined_df = pd.merge(cleaned_df, research_df, on='Tranc_Year', how="left")

In [76]:
combined_df.columns

Index(['id', 'Tranc_YearMonth', 'town', 'flat_type', 'block', 'street_name',
       'storey_range', 'floor_area_sqm', 'flat_model', 'lease_commence_date',
       'resale_price', 'Tranc_Year', 'Tranc_Month', 'mid_storey', 'lower',
       'upper', 'mid', 'full_flat_type', 'address', 'floor_area_sqft',
       'price_per_sqft', 'hdb_age', 'max_floor_lvl', 'year_completed',
       'residential', 'commercial', 'market_hawker', 'multistorey_carpark',
       'precinct_pavilion', 'total_dwelling_units', '1room_sold', '2room_sold',
       '3room_sold', '4room_sold', '5room_sold', 'exec_sold', 'multigen_sold',
       'studio_apartment_sold', '1room_rental', '2room_rental', '3room_rental',
       'other_room_rental', 'postal', 'Latitude', 'Longitude', 'planning_area',
       'Mall_Nearest_Distance', 'Mall_Within_500m', 'Mall_Within_1km',
       'Mall_Within_2km', 'Hawker_Nearest_Distance', 'Hawker_Within_500m',
       'Hawker_Within_1km', 'Hawker_Within_2km', 'hawker_food_stalls',
       'hawker_market_stalls', 'mrt_nearest_distance', 'mrt_name',
       'bus_interchange', 'mrt_interchange', 'mrt_latitude', 'mrt_longitude',
       'bus_stop_nearest_distance', 'bus_stop_name', 'bus_stop_latitude',
       'bus_stop_longitude', 'pri_sch_nearest_distance', 'pri_sch_name',
       'vacancy', 'pri_sch_affiliation', 'pri_sch_latitude',
       'pri_sch_longitude', 'sec_sch_nearest_dist', 'sec_sch_name',
       'cutoff_point', 'affiliation', 'sec_sch_latitude', 'sec_sch_longitude',
       'absd_foreigner', 'ltv_limit_2nd_loan', 'bto_launched', 'mop_flats'],
      dtype='str')

In [77]:
combined_df.to_csv("combined.csv", index=False)

This notebook transitions the dataset from: structurally cleaned to fully model-ready

It performs:

- Final imputation
- Categorical encoding
- Multicollinearity prevention
- Data integrity checks
- Final export